### ISSUE TITLE
How to fix the probelm about multiprocesing.Process().start

### ISSUE THREAD

**Issue by cumttang** [deepmind/scalable_agent#6]
Hello, I met a strange problem when I run the example in py_process.py:

Example:

class Zeros(object):

    def __init__(self, dim0):
      self._dim0 = dim0

    def compute(self, dim1):
      return np.zeros([self._dim0, dim1], dtype=np.int32)

    @staticmethod
    def _tensor_specs(method_name, kwargs, constructor_kwargs):
      dim0 = constructor_kwargs['dim0']
      dim1 = kwargs['dim1']
      if method_name == 'compute':
        return tf.contrib.framework.TensorSpec([dim0, dim1], tf.int32)

    with tf.Graph().as_default():
      p = py_process.PyProcess(Zeros, 1)
      result = p.proxy.compute(2)

    with tf.train.SingularMonitoredSession(
        hooks=[py_process.PyProcessHook()]) as session:
      print(session.run(result))  # Prints [[0, 0]].

The problem occured when the code run on:

 **"
self._process = multiprocessing.Process(
        target=self._worker_fn,
        args=(self._type, self._constructor_kwargs, in_))
self._process.start()
"**

The interpreter reported that:

   **zip(function_utils.fn_args(getattr(self._type, name))[1:], args))
AttributeError: type object 'Zeros' has no attribute '\_\_getstate\_\_'**

Is there any thing wrong with multiprocessing? I'm using python3.5 on win 10.

**Comment by lespeholt** [comment]
Just verified that it works on Python 2.7 so could be a v3 issue.

**Comment by lespeholt** [comment]
Can you post the full stack trace?

**Comment by cumttang** [comment]
I fix it when I met "\_\_getstate\_\_" requirement in py_process.py:
 # For additional methods
  def __getattr__(self, name):
    def call(*args):

      **# Fix "__getstate__" bugs
      if name=="__getstate__":
        return None**

      kwargs = dict(
          zip(function_utils.fn_args(getattr(self._type, name))[1:], args))
      specs = self._type._tensor_specs(name, kwargs, self._constructor_kwargs)

      if specs is None:
        raise ValueError(
            'No tensor specifications were provided for: %s' % name)

      flat_dtypes = nest.flatten(nest.map_structure(lambda s: s.dtype, specs))
      flat_shapes = nest.flatten(nest.map_structure(lambda s: s.shape, specs))

      def py_call(*args):
        try:
          **# Fix Bugs, from byte transform to string!
          new_args = list()
          for arg in args:
            if isinstance(arg, bytes):
              arg = str(arg, encoding="utf-8")
            new_args.append(arg)
          new_args = tuple(new_args)
          # Fix Bugs, From byte transform to string.**

          self._out.send(new_args)
          result = self._out.recv()
          if isinstance(result, Exception):
            raise result
          if result is not None:
            return result
        except Exception as e:
          if isinstance(e, IOError):
            raise StopIteration()  # Clean exit.
          else:
            raise

      result = tf.py_func(py_call, (name,) + tuple(args), flat_dtypes, name=name)

      if isinstance(result, tf.Operation):
        return result

      for t, shape in zip(result, flat_shapes):
        t.set_shape(shape)
      return nest.pack_sequence_as(specs, result)
    return call

**Comment by cumttang** [comment]
But I have another question, Can I use the IMPALA withtout Sonnet?
Is there any method using without placeholder and session to do the feed forward part.

**Comment by lespeholt** [comment]
We don't actually use placeholders. But you do need a session to run the code. Sonnet can easily be replaced with tf.layers/tf.keras, etc.

**Comment by cumttang** [comment]
I will try it. Thanks for your patient!

**Comment by halessi** [comment]
Running this in python 2.7.15 with tensorflow 1.12 still unfortunately gives: 
``PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed``

Running with python 3.6 gives similar issue.
